// tests/e2e/e2e_runner.cpp
//
// See e2e_runner.hpp. Command-line construction follows the proven
// test_trace_replay / test_step_cooldown pattern: forward slashes everywhere
// and the whole command double-quoted so cmd.exe handles `>` redirection.

#include "e2e_runner.hpp"

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <regex>
#include <sstream>

namespace e2e {

bool write_input_script(const std::filesystem::path& path,
                        const std::vector<InputEvent>& events) {
    std::ofstream f(path, std::ios::trunc);
    if (!f) return false;
    f << "# input script generated by tests/e2e/e2e_runner.cpp\n";
    for (const auto& ev : events) {
        f << "frame " << ev.frame << " "
          << (ev.down ? "keydown" : "keyup") << " " << ev.key << "\n";
    }
    return f.good();
}

namespace {
std::string fwd(const std::filesystem::path& p) {
    std::string s = p.string();
    std::replace(s.begin(), s.end(), '\\', '/');
    return s;
}

std::vector<std::string> read_lines(const std::filesystem::path& path) {
    std::vector<std::string> out;
    std::ifstream f(path);
    std::string line;
    while (std::getline(f, line)) out.push_back(line);
    return out;
}
}  // namespace

RunResult run_app(const RunSpec& spec) {
    RunResult res;

    const std::filesystem::path build_dir = spec.root / "build";
    std::error_code ec;
    std::filesystem::create_directories(build_dir, ec);

    const std::filesystem::path out_path = build_dir / (spec.out_name + ".out");

    // The debug log lands at <root>/resf2_debug.log (main.cpp) — older builds
    // wrote <root>/assets/resf2_debug.log. Delete both candidates before the
    // run so a stale log can never be mistaken for this run's.
    const std::filesystem::path log_root = spec.root / "resf2_debug.log";
    const std::filesystem::path log_assets =
        spec.root / "assets" / "resf2_debug.log";
    std::filesystem::remove(log_root, ec);
    std::filesystem::remove(log_assets, ec);

    std::string cmd = "\"\"" + fwd(spec.app) + "\" --assets \"" + fwd(spec.root) +
                      "\" --input-script \"" + fwd(spec.script) + "\"";
    for (const auto& a : spec.extra_args) cmd += " \"" + a + "\"";
    cmd += " --max-frames " + std::to_string(spec.max_frames);
    if (spec.dump_state) cmd += " --dump-state";
    if (spec.no_log) cmd += " --no-log";
    cmd += " > \"" + fwd(out_path) + "\" 2>&1\"";

    std::fprintf(stderr, "[e2e] %s\n", cmd.c_str());
    res.launched = true;
    res.exit_code = std::system(cmd.c_str());

    std::ifstream f(out_path, std::ios::binary);
    if (f) {
        std::ostringstream ss;
        ss << f.rdbuf();
        res.stdout_text = ss.str();
    }
    res.stdout_lines = read_lines(out_path);

    // Prefer the <root> location (current main.cpp); fall back to assets/.
    if (std::filesystem::exists(log_root)) {
        res.log_lines = read_lines(log_root);
    } else if (std::filesystem::exists(log_assets)) {
        res.log_lines = read_lines(log_assets);
    }
    return res;
}

std::vector<StateFrame> parse_state_frames(const RunResult& run) {
    std::vector<StateFrame> out;
    static const std::regex re(
        R"(\[STATE\] f=(\d+) ms=(-?\d+) ha=(\d+) anim='([^']*)' move='([^']*)' px=([-\d.]+) py=([-\d.]+))");
    static const std::regex re_enemy(R"(ex=([-\d.]+) ey=([-\d.]+))");
    for (const auto& line : run.stdout_lines) {
        std::smatch m;
        if (!std::regex_search(line, m, re)) continue;
        StateFrame fr;
        fr.frame = std::stoll(m[1]);
        fr.move_state = std::stoi(m[2]);
        fr.hit_anim = (unsigned)std::stoul(m[3]);
        fr.anim = m[4];
        fr.move = m[5];
        fr.px = std::stof(m[6]);
        fr.py = std::stof(m[7]);
        std::smatch me;
        if (std::regex_search(line, me, re_enemy)) {
            fr.ex = std::stof(me[1]);
            fr.ey = std::stof(me[2]);
        }
        std::smatch ma;
        static const std::regex re_anchor(R"(anchor_x=([-\d.]+))");
        if (std::regex_search(line, ma, re_anchor))
            fr.anchor_x = std::stof(ma[1]);
        std::smatch mf;
        static const std::regex re_facing(R"(fr=(\d) ef=(\d))");
        if (std::regex_search(line, mf, re_facing)) {
            fr.fr = std::stoi(mf[1]);
            fr.ef = std::stoi(mf[2]);
        }
        fr.raw = line;
        out.push_back(fr);
    }
    return out;
}

int first_frame_with(const std::vector<StateFrame>& frames,
                     const std::string& anim, long long after) {
    for (const auto& fr : frames)
        if (fr.frame > after && fr.anim == anim) return (int)fr.frame;
    return -1;
}

std::vector<std::string> filter_lines(const std::vector<std::string>& lines,
                                      const std::string& needle) {
    std::vector<std::string> out;
    for (const auto& l : lines)
        if (l.find(needle) != std::string::npos) out.push_back(l);
    return out;
}

}  // namespace e2e
