<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="Movesxml">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="Templates" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Template" type="move" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="Moves" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Move" type="move" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:complexType name="move">
  <xs:all>
    <xs:element name="Shop" minOccurs="0"/>
    <xs:element name="SetDirection" type="vector" minOccurs="0"/>
    <xs:element name="Align" minOccurs="0">
      <xs:complexType>
        <xs:all>
          <xs:element name="Pivot" type="mypoint" />
          <xs:element name="Position" type="point"/>
        </xs:all>
        <xs:attribute name="Axis" use="optional"/>
      </xs:complexType>
    </xs:element>
    <xs:element name="Events" minOccurs="0">
      <xs:complexType>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element name="EveryFrame" />
          <xs:element name="RoundStudyStart" />
          <xs:element name="Hit" />
          <xs:element name="WallHit" />
          <xs:element name="KeyPressed" />
          <xs:element name="AnimationStart" />
          <xs:element name="AnimationEnd" />
          <xs:element name="IntervalStart" />
          <xs:element name="IntervalEnd" />
        </xs:choice>
      </xs:complexType>
    </xs:element>
    <xs:element name="Conditions" minOccurs="0">
      <xs:complexType>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element name="Keys" />
          <xs:element name="RoundStudy" />
          <xs:element name="RoundResult" />
          <xs:element name="Distance" />
          <xs:element name="CurrentAnimation" />
          <xs:element name="CurrentInterval" />
          <xs:element name="PhysicsFrameNumber" />
          <xs:element name="Player" />
          <xs:element name="Health" />
          <xs:element name="Operator" />
        </xs:choice>
      </xs:complexType>
    </xs:element>
    <xs:element name="Locks" minOccurs="0">
      <xs:complexType>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element name="Item" />
          <xs:element name="Operator" />
        </xs:choice>
      </xs:complexType>
    </xs:element>
    <xs:element name="Intervals" minOccurs="0">
      <xs:complexType>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element name="Interval" type="interval" />
        </xs:choice>
      </xs:complexType>
    </xs:element>
    <xs:element name="Sounds" minOccurs="0">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="Sound" minOccurs="0" maxOccurs="unbounded">
            <xs:complexType>
              <xs:attribute name="Name" use="required"/>
              <xs:attribute name="Frame" type="xs:integer" />
              <xs:attribute name="OnHit" type="flag" />
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:complexType>
    </xs:element>
  </xs:all>
  <xs:anyAttribute processContents="lax"/>
</xs:complexType>

<xs:simpleType name="player">
  <xs:restriction base="xs:string">
    <xs:enumeration value="Me"/>
    <xs:enumeration value="Enemy"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="flag">
  <xs:restriction base="xs:integer">
    <xs:enumeration value="0" />
    <xs:enumeration value="1" />
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="vector">
  <xs:all>
    <xs:element name="From" type="point" minOccurs="0" />
    <xs:element name="To" type="point" minOccurs="0" />
    <xs:element name="Impulse" minOccurs="0">
      <xs:complexType>
        <xs:attribute name="Reverse" type="flag" />
      </xs:complexType>
    </xs:element>
  </xs:all>
</xs:complexType>

<xs:complexType name="point">
  <xs:attribute name="Player" type="player"/>
  <xs:attributeGroup ref="object"/>
</xs:complexType>

<xs:complexType name="mypoint">
  <xs:attributeGroup ref="object"/>
</xs:complexType>

<xs:attributeGroup name="object">
  <xs:attribute name="Object" use="required">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="Animation"/>
        <xs:enumeration value="Pivot"/>
        <xs:enumeration value="Nodes"/>
        <xs:enumeration value="Wall"/>
        <xs:enumeration value="Floor"/>
        <xs:enumeration value="COM"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>
  <xs:attribute name="Part" />
</xs:attributeGroup >

<xs:complexType name="interval" mixed="true">
  <xs:all minOccurs="0">
    <xs:element name="AttackingParts" minOccurs="0">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="Edge" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
              <xs:attribute name="Name" use="required" />
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:complexType>
    </xs:element>
    <xs:element name="Damage">
      <xs:complexType>
        <xs:sequence minOccurs="0">
          <xs:element name="FactorItem" />
        </xs:sequence>
        <xs:attribute name="Value" type="xs:integer" use="required" />
      </xs:complexType>
    </xs:element>
    <xs:element name="Impulse" minOccurs="0">
      <xs:complexType>
        <xs:attribute name="X" type="xs:integer" use="required" />
        <xs:attribute name="Y" type="xs:integer" use="required" />
        <xs:attribute name="Z" type="xs:integer" use="required" />
      </xs:complexType>
    </xs:element>
    <xs:element name="Hit" type="hit" minOccurs="0"/>
  </xs:all>
  <xs:attribute name="Type">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="Block"/>
        <xs:enumeration value="Invulnerable"/>
        <xs:enumeration value="Attack"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>
  <xs:attribute name="Name" />
  <xs:attribute name="Start" type="xs:integer" />
  <xs:attribute name="End" type="xs:integer" />
</xs:complexType>

<xs:complexType name="hit">
  <xs:attribute name="Name" />
</xs:complexType>

</xs:schema>