#!/usr/bin/env python3
"""record_inputs.py — convert oracle [INPUT-REC] console lines to a replay file.

The tracer logs every effective input (post-Za-gating N0a press / O0a
release) as:
    [INPUT-REC] {"f":208,"i":3,"m":"N0a","c":9,"x":0,"t":0}
This script orders them by (frame, sequence) and writes the exact-replay
script (same format family as input_phase1.txt):
    atframe 208 press 9 0 0
    atframe 215 release 9 0 0

Usage:
    python reference/tools/record_inputs.py [console.log] [recorded_inputs.txt]

Replay bypasses DOM + Za lesson gates (direct fight.N0a/O0a calls page-side),
so the recorded effective stream reproduces deterministically.
"""
import sys
import json
import hashlib

HEADER = """# Recorded effective inputs (post-Za-gating N0a/O0a stream).
# Generated by reference/tools/record_inputs.py from [INPUT-REC] console lines.
# Replay: OracleShell --input-script <this file> (page-side exact replay).
"""


def main():
    inp = sys.argv[1] if len(sys.argv) > 1 else "reference/traces/console.log"
    outp = sys.argv[2] if len(sys.argv) > 2 else "reference/traces/recorded_inputs.txt"
    events = []
    n_other = 0
    with open(inp, encoding="utf-8", errors="replace") as fh:
        for line in fh:
            i = line.find("[INPUT-REC] ")
            if i < 0:
                continue
            payload = line[i + len("[INPUT-REC] "):].strip()
            if not payload.startswith("{"):
                n_other += 1
                continue
            try:
                o = json.loads(payload)
            except json.JSONDecodeError:
                n_other += 1
                continue
            if o.get("m") not in ("N0a", "O0a"):
                n_other += 1
                continue
            try:
                f = int(o["f"])
                seq = int(o["i"])
                c = int(o["c"])
            except (KeyError, TypeError, ValueError):
                n_other += 1
                continue
            x = o.get("x")
            x = int(x) if isinstance(x, int) else 0
            t = o.get("t")
            t = int(t) if isinstance(t, int) else 0
            verb = "press" if o["m"] == "N0a" else "release"
            events.append((f, seq, verb, c, x, t))

    events.sort(key=lambda e: (e[0], e[1]))
    lines = [HEADER]
    prev_f = None
    for (f, _seq, verb, c, x, t) in events:
        if prev_f is not None and f < prev_f:
            print("WARN: non-monotonic frame %d after %d" % (f, prev_f))
        prev_f = f
        lines.append("atframe %d %s %d %d %d\n" % (f, verb, c, x, t))

    with open(outp, "w", encoding="utf-8", newline="\n") as fh:
        fh.writelines(lines)
    with open(outp, "rb") as fh:
        digest = hashlib.sha256(fh.read()).hexdigest()
    print("input events: %d (skipped: %d)" % (len(events), n_other))
    if events:
        print("frame range: %d..%d" % (events[0][0], events[-1][0]))
    print("sha256(%s) = %s" % (outp, digest))
    return 0


if __name__ == "__main__":
    sys.exit(main())
